import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RowDirective } from "./row/row.directive";
import { ContainerDirective } from "./container/container.directive";

import {
  ColXS0Directive,
  ColXS1Directive,
  ColXS2Directive,
  ColXS3Directive,
  ColXS4Directive,
  ColXS5Directive,
  ColXS6Directive,
  ColXS7Directive,
  ColXS8Directive,
  ColXS9Directive,
  ColXS10Directive,
  ColXS11Directive,
  ColXS12Directive,
  ColSM0Directive,
  ColSM1Directive,
  ColSM2Directive,
  ColSM3Directive,
  ColSM4Directive,
  ColSM5Directive,
  ColSM6Directive,
  ColSM7Directive,
  ColSM8Directive,
  ColSM9Directive,
  ColSM10Directive,
  ColSM11Directive,
  ColSM12Directive,
  ColMD0Directive,
  ColMD1Directive,
  ColMD2Directive,
  ColMD3Directive,
  ColMD4Directive,
  ColMD5Directive,
  ColMD6Directive,
  ColMD7Directive,
  ColMD8Directive,
  ColMD9Directive,
  ColMD10Directive,
  ColMD11Directive,
  ColMD12Directive,
  ColLG0Directive,
  ColLG1Directive,
  ColLG2Directive,
  ColLG3Directive,
  ColLG4Directive,
  ColLG5Directive,
  ColLG6Directive,
  ColLG7Directive,
  ColLG8Directive,
  ColLG9Directive,
  ColLG10Directive,
  ColLG11Directive,
  ColLG12Directive,
  ColXL0Directive,
  ColXL1Directive,
  ColXL2Directive,
  ColXL3Directive,
  ColXL4Directive,
  ColXL5Directive,
  ColXL6Directive,
  ColXL7Directive,
  ColXL8Directive,
  ColXL9Directive,
  ColXL10Directive,
  ColXL11Directive,
  ColXL12Directive,
  ColDirective,
} from "./col/col.directive";

@NgModule({
  declarations: [
    RowDirective,
    ContainerDirective,

    ColDirective,

    // ColXS0Directive,
    // ColXS1Directive,
    // ColXS2Directive,
    // ColXS3Directive,
    // ColXS4Directive,
    // ColXS5Directive,
    // ColXS6Directive,
    // ColXS7Directive,
    // ColXS8Directive,
    // ColXS9Directive,
    // ColXS10Directive,
    // ColXS11Directive,
    // ColXS12Directive,

    // ColSM0Directive,
    // ColSM1Directive,
    // ColSM2Directive,
    // ColSM3Directive,
    // ColSM4Directive,
    // ColSM5Directive,
    // ColSM6Directive,
    // ColSM7Directive,
    // ColSM8Directive,
    // ColSM9Directive,
    // ColSM10Directive,
    // ColSM11Directive,
    // ColSM12Directive,

    // ColMD0Directive,
    // ColMD1Directive,
    // ColMD2Directive,
    // ColMD3Directive,
    // ColMD4Directive,
    // ColMD5Directive,
    // ColMD6Directive,
    // ColMD7Directive,
    // ColMD8Directive,
    // ColMD9Directive,
    // ColMD10Directive,
    // ColMD11Directive,
    // ColMD12Directive,

    // ColLG0Directive,
    // ColLG1Directive,
    // ColLG2Directive,
    // ColLG3Directive,
    // ColLG4Directive,
    // ColLG5Directive,
    // ColLG6Directive,
    // ColLG7Directive,
    // ColLG8Directive,
    // ColLG9Directive,
    // ColLG10Directive,
    // ColLG11Directive,
    // ColLG12Directive,

    // ColXL0Directive,
    // ColXL1Directive,
    // ColXL2Directive,
    // ColXL3Directive,
    // ColXL4Directive,
    // ColXL5Directive,
    // ColXL6Directive,
    // ColXL7Directive,
    // ColXL8Directive,
    // ColXL9Directive,
    // ColXL10Directive,
    // ColXL11Directive,
    // ColXL12Directive,
  ],
  imports: [CommonModule],
  exports: [
    RowDirective,
    ContainerDirective,

    ColDirective,

    // ColXS0Directive,
    // ColXS1Directive,
    // ColXS2Directive,
    // ColXS3Directive,
    // ColXS4Directive,
    // ColXS5Directive,
    // ColXS6Directive,
    // ColXS7Directive,
    // ColXS8Directive,
    // ColXS9Directive,
    // ColXS10Directive,
    // ColXS11Directive,
    // ColXS12Directive,

    // ColSM0Directive,
    // ColSM1Directive,
    // ColSM2Directive,
    // ColSM3Directive,
    // ColSM4Directive,
    // ColSM5Directive,
    // ColSM6Directive,
    // ColSM7Directive,
    // ColSM8Directive,
    // ColSM9Directive,
    // ColSM10Directive,
    // ColSM11Directive,
    // ColSM12Directive,

    // ColMD0Directive,
    // ColMD1Directive,
    // ColMD2Directive,
    // ColMD3Directive,
    // ColMD4Directive,
    // ColMD5Directive,
    // ColMD6Directive,
    // ColMD7Directive,
    // ColMD8Directive,
    // ColMD9Directive,
    // ColMD10Directive,
    // ColMD11Directive,
    // ColMD12Directive,

    // ColLG0Directive,
    // ColLG1Directive,
    // ColLG2Directive,
    // ColLG3Directive,
    // ColLG4Directive,
    // ColLG5Directive,
    // ColLG6Directive,
    // ColLG7Directive,
    // ColLG8Directive,
    // ColLG9Directive,
    // ColLG10Directive,
    // ColLG11Directive,
    // ColLG12Directive,

    // ColXL0Directive,
    // ColXL1Directive,
    // ColXL2Directive,
    // ColXL3Directive,
    // ColXL4Directive,
    // ColXL5Directive,
    // ColXL6Directive,
    // ColXL7Directive,
    // ColXL8Directive,
    // ColXL9Directive,
    // ColXL10Directive,
    // ColXL11Directive,
    // ColXL12Directive,
  ],
})
export class LibLayoutModule {}
